// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrufeodegwmkmrekdkxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJydWZlb2RlZ3dta21yZWtka3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMTUzMzIsImV4cCI6MjA1MTc5MTMzMn0.LpWJh0ezSPOT09ADwIdy4vY1unzmug-qV6DT1al_oRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);